// This file is generated by scripts/generate-case-study-registry.mjs.
// The build regenerates it from sibling case-study files.
import type { CaseStudy } from "./types";
import { caseStudy as aamcExtension } from "./aamc-extension";

export const caseStudies = [aamcExtension] satisfies CaseStudy[];
